
disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - line_length
 - force_try
 - force_cast
 - operator_whitespace 

# Change warning back to 20
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 200

# Take this out, once fixed
type_body_length:
  warning: 2000

function_body_length:
  warning: 2000

identifier_name:
  allowed_symbols: "_"
  min_length: 1
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

